# .github/workflows/main.yml
name: Test Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
          
      - name: Commit changes
        run: |
          python script.py >> README.md
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md # Specify the file(s) you want to commit
          git commit -m "Update README.md"
          git push origin main
